export interface ModeloPage {
	slug: string
	brand: string
	model: string
	metaTitle: string
	metaDescription: string
	keywords: string[]
	resumo: string
	versoes: string[]
	faixaPreco: { novo: string; seminovo: string }
	diferenciais: { label: string; texto: string }[]
	perfilIdeal: string
	quandoNaoComprar: string
	faq: { pergunta: string; resposta: string }[]
	modelosRelacionados: { nome: string; href: string }[]
}

export const MODELOS: ModeloPage[] = [
	{
		slug: 'porsche-911',
		brand: 'Porsche',
		model: '911',
		metaTitle: 'Porsche 911 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Porsche 911 à venda no Brasil com procedência verificada. Confira versões disponíveis, faixa de preço e estoque real. Attra Veículos.',
		keywords: ['porsche 911 à venda', 'comprar porsche 911 brasil', 'porsche 911 preço', 'porsche 911 seminovo'],
		resumo: 'O Porsche 911 é o esportivo de referência para quem busca performance pura com uso diário. Comprado por entusiastas, colecionadores e motoristas que priorizam dirigibilidade acima de tudo.',
		versoes: ['Carrera', 'Carrera S', 'Carrera 4S', 'Turbo', 'Turbo S', 'GT3', 'GT3 RS', 'Targa'],
		faixaPreco: { novo: 'R$ 800 mil a R$ 3,5 milhões', seminovo: 'R$ 500 mil a R$ 2,5 milhões' },
		diferenciais: [
			{ label: 'Performance', texto: 'Motor boxer traseiro com distribuição de peso otimizada. Aceleração de 0 a 100 km/h em menos de 4 segundos nas versões Turbo.' },
			{ label: 'Status', texto: 'Reconhecido globalmente como o esportivo mais icônico do mundo. Silhueta inconfundível que dispensa apresentações.' },
			{ label: 'Uso', texto: 'Um dos poucos supercarros que funciona como carro diário. Porta-malas dianteiro prático, consumo razoável para a categoria.' },
		],
		perfilIdeal: 'Entusiasta que quer performance real no dia a dia. Pessoas que valorizam engenharia, tradição esportiva e precisão mecânica. Ideal para quem busca um carro que entrega emoção na pista e conforto na cidade.',
		quandoNaoComprar: 'Se a prioridade é espaço interno ou conforto de passageiros traseiros. Não é a escolha certa para quem precisa de um carro familiar ou quer apenas status visual sem interesse em dirigibilidade.',
		faq: [
			{ pergunta: 'Qual o preço do Porsche 911 no Brasil?', resposta: 'O valor varia amplamente conforme versão (Carrera, Turbo S, GT3 RS), quilometragem e estado geral. Consulte nosso estoque para preços atualizados e condições reais de cada unidade disponível.' },
			{ pergunta: 'A manutenção do 911 é cara?', resposta: 'O custo de manutenção é compatível com a categoria de esportivos premium. Versões cerâmicas têm peças de desgaste mais caras. Revisões na rede autorizada garantem valorização e segurança do veículo.' },
			{ pergunta: 'O 911 é um bom carro para uso diário?', resposta: 'Sim. É um dos esportivos mais adaptados ao uso diário do mercado. Possui porta-malas funcional, visibilidade adequada e modos de condução que equilibram conforto e performance.' },
			{ pergunta: 'A Attra entrega o 911 em todo o Brasil?', resposta: 'Sim. A Attra realiza entrega em caminhão fechado com seguro completo e rastreamento em tempo real para todo o território nacional.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW M3', href: '/comprar/modelo/bmw-m3' },
			{ nome: 'Mercedes C63 AMG', href: '/comprar/modelo/mercedes-c63-amg' },
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
		],
	},
	{
		slug: 'bmw-m3',
		brand: 'BMW',
		model: 'M3',
		metaTitle: 'BMW M3 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'BMW M3 à venda no Brasil com procedência verificada. Confira versões, faixa de preço e estoque real. Attra Veículos.',
		keywords: ['bmw m3 à venda', 'comprar bmw m3 brasil', 'bmw m3 preço', 'bmw m3 seminovo'],
		resumo: 'O BMW M3 é referência entre sedans esportivos. Projetado para quem quer performance de pista com a praticidade de um sedan premium no dia a dia.',
		versoes: ['M3 Standard', 'M3 Competition', 'M3 Competition xDrive', 'M3 CS'],
		faixaPreco: { novo: 'R$ 700 mil a R$ 1,2 milhão', seminovo: 'R$ 400 mil a R$ 900 mil' },
		diferenciais: [
			{ label: 'Performance', texto: 'Motor S58 de 6 cilindros em linha biturbo com até 550 cv na versão CS. Resposta linear e progressiva, ideal para condução esportiva.' },
			{ label: 'Status', texto: 'Ícone do segmento M da BMW. Reconhecido mundialmente como um dos melhores sedans esportivos já produzidos.' },
			{ label: 'Uso', texto: 'Sedan de 4 portas com espaço para passageiros e bagagem. Funciona perfeitamente como carro principal com performance de pista.' },
		],
		perfilIdeal: 'Motorista que busca precisão de condução e feedback mecânico em um pacote funcional. Ideal para quem precisa de 4 portas sem abrir mão de performance real.',
		quandoNaoComprar: 'Se você prioriza conforto de rodagem acima de tudo. A suspensão firme e o foco esportivo podem incomodar em deslocamentos longos no dia a dia urbano.',
		faq: [
			{ pergunta: 'Qual o preço do BMW M3 no Brasil?', resposta: 'O valor depende da geração (F80, G80) e versão (Standard, Competition, CS). Seminovos de gerações anteriores são mais acessíveis. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'O M3 é confiável?', resposta: 'Sim. O motor S58 é considerado robusto e confiável desde que as revisões sejam feitas na rede autorizada. A manutenção preventiva é essencial para longevidade.' },
			{ pergunta: 'M3 Competition ou M3 CS?', resposta: 'O Competition é a versão mais equilibrada para uso misto. O CS é focado em pista com menos conforto, peso reduzido e potência superior. Para uso diário, o Competition é mais indicado.' },
			{ pergunta: 'A Attra entrega o M3 em todo o Brasil?', resposta: 'Sim. Entrega especializada em caminhão fechado com seguro completo para todo o território nacional.' },
		],
		modelosRelacionados: [
			{ nome: 'Mercedes C63 AMG', href: '/comprar/modelo/mercedes-c63-amg' },
			{ nome: 'Audi RS6', href: '/comprar/modelo/audi-rs6' },
			{ nome: 'Porsche 911', href: '/comprar/modelo/porsche-911' },
		],
	},
	{
		slug: 'mercedes-c63-amg',
		brand: 'Mercedes-Benz',
		model: 'C63 AMG',
		metaTitle: 'Mercedes C63 AMG à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Mercedes C63 AMG à venda no Brasil. V8 biturbo, performance e luxo. Confira preço, versões e estoque real. Attra Veículos.',
		keywords: ['mercedes c63 amg à venda', 'comprar c63 amg brasil', 'mercedes c63 preço', 'c63 amg seminovo'],
		resumo: 'O Mercedes-AMG C 63 combina brutalidade mecânica com luxo refinado. Escolhido por quem quer um sedan esportivo com presença imponente e interior premium.',
		versoes: ['C 63', 'C 63 S', 'C 63 S Coupé', 'C 63 S E Performance'],
		faixaPreco: { novo: 'R$ 800 mil a R$ 1,3 milhão', seminovo: 'R$ 350 mil a R$ 800 mil' },
		diferenciais: [
			{ label: 'Performance', texto: 'Motor V8 4.0L biturbo com até 510 cv nas versões S (geração W205). Torque brutal disponível desde baixas rotações, entregando aceleração visceral.' },
			{ label: 'Status', texto: 'O selo AMG é sinônimo de exclusividade. Presença de rua inigualável entre sedans esportivos, com sonoridade que o diferencia de qualquer concorrente.' },
			{ label: 'Uso', texto: 'Interior Mercedes com acabamento superior. Conforto para viagens longas com a capacidade de ser agressivo quando exigido.' },
		],
		perfilIdeal: 'Quem busca experiência sensorial completa: ronco de V8, interior luxuoso e presença marcante. Ideal para motoristas que valorizam a combinação de potência bruta com refinamento.',
		// REVISAR ANUALMENTE — referência a "nova geração" envelhece com lançamentos
		quandoNaoComprar: 'Se pureza de condução e feedback de volante são prioridade absoluta. O C63 é mais pesado e menos comunicativo que rivais focados em pista. A nova geração com 4 cilindros híbrido também divide opiniões entre puristas.',
		faq: [
			{ pergunta: 'Qual o preço do C63 AMG no Brasil?', resposta: 'O valor varia conforme geração (V8 W205 ou híbrido W206) e versão. As versões V8 estão em tendência de valorização. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'O V8 do C63 vai acabar?', resposta: 'A geração W206 já utiliza motor 4 cilindros híbrido. Porém, as versões V8 (W205) continuam sendo as mais procuradas no mercado de seminovos pela sonoridade e caráter único.' },
			{ pergunta: 'C63 AMG ou BMW M3?', resposta: 'O M3 oferece condução mais pura e comunicativa. O C63 entrega experiência mais visceral com o V8 e interior mais luxuoso. A escolha depende do perfil do motorista.' },
			{ pergunta: 'A Attra entrega o C63 em todo o Brasil?', resposta: 'Sim. Entrega em caminhão fechado com seguro completo e rastreamento para todo o país.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW M3', href: '/comprar/modelo/bmw-m3' },
			{ nome: 'Audi RS6', href: '/comprar/modelo/audi-rs6' },
			{ nome: 'Mercedes GLE', href: '/comprar/modelo/mercedes-gle' },
		],
	},
	{
		slug: 'audi-rs6',
		brand: 'Audi',
		model: 'RS6',
		metaTitle: 'Audi RS6 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Audi RS6 Avant à venda no Brasil. Performance de superesportivo em formato perua. Preço, versões e estoque real. Attra Veículos.',
		keywords: ['audi rs6 à venda', 'comprar audi rs6 brasil', 'audi rs6 preço', 'rs6 avant seminovo'],
		resumo: 'O Audi RS6 Avant é a perua mais rápida do mundo. Projetado para quem recusa compromissos entre performance extrema e praticidade no dia a dia.',
		versoes: ['RS6 Avant', 'RS6 Avant Performance'],
		faixaPreco: { novo: 'R$ 1 milhão a R$ 1,5 milhão', seminovo: 'R$ 700 mil a R$ 1,2 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Motor V8 4.0L biturbo com 600 cv e tração Quattro. Aceleração de 0 a 100 km/h em 3,6 segundos em formato perua.' },
			{ label: 'Status', texto: 'Discretamente brutal. Visualmente uma perua elegante que esconde performance de superesportivo. O carro de quem entende sem precisar ostentar.' },
			{ label: 'Uso', texto: 'Espaço interno generoso, porta-malas de 565 litros e conforto de viagem. Funciona como carro familiar com capacidade de ultrapassar supercarros.' },
		],
		perfilIdeal: 'Entusiasta prático. Quem quer levar a família e a bagagem sem abrir mão de 600 cv e aceleração de superesportivo. Ideal para viagens longas com performance sob demanda.',
		quandoNaoComprar: 'Se o objetivo é um carro compacto para uso urbano. O RS6 é grande e pesado, com consumo elevado. Não é a escolha para quem busca economia ou agilidade em espaços apertados.',
		faq: [
			{ pergunta: 'Qual o preço do Audi RS6 no Brasil?', resposta: 'O RS6 Avant é posicionado no topo do segmento, com valor variando conforme versão e quilometragem. Consulte nosso estoque para preços atualizados e disponibilidade.' },
			{ pergunta: 'O RS6 serve como carro de família?', resposta: 'Perfeitamente. Possui 5 lugares confortáveis, porta-malas generoso e modos de condução que o transformam de uma perua confortável a um superesportivo em segundos.' },
			{ pergunta: 'Manutenção do RS6 é cara?', resposta: 'O custo de manutenção é compatível com a categoria de superesportivos. O motor V8 biturbo requer atenção especial ao óleo e sistema de refrigeração. Revisões na rede Audi garantem qualidade.' },
			{ pergunta: 'A Attra entrega o RS6 em todo o Brasil?', resposta: 'Sim. Entrega nacional em caminhão fechado com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW M3', href: '/comprar/modelo/bmw-m3' },
			{ nome: 'Mercedes C63 AMG', href: '/comprar/modelo/mercedes-c63-amg' },
			{ nome: 'Audi Q8', href: '/comprar/modelo/audi-q8' },
		],
	},
	{
		slug: 'porsche-cayenne',
		brand: 'Porsche',
		model: 'Cayenne',
		metaTitle: 'Porsche Cayenne à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Porsche Cayenne à venda no Brasil. SUV premium com DNA esportivo. Preço, versões e estoque real. Attra Veículos.',
		keywords: ['porsche cayenne à venda', 'comprar porsche cayenne brasil', 'cayenne preço', 'cayenne seminovo'],
		resumo: 'O Porsche Cayenne é o SUV que trouxe performance esportiva para o segmento de utilitários premium. Comprado por quem quer versatilidade sem abrir mão do DNA Porsche.',
		versoes: ['Cayenne', 'Cayenne S', 'Cayenne GTS', 'Cayenne Turbo', 'Cayenne Turbo GT', 'Cayenne E-Hybrid'],
		faixaPreco: { novo: 'R$ 600 mil a R$ 1,8 milhão', seminovo: 'R$ 350 mil a R$ 1,3 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Chassis derivado do 911 com suspensão adaptativa. Versão Turbo GT com 640 cv é o SUV mais rápido do Nürburgring.' },
			{ label: 'Status', texto: 'O SUV premium que definiu a categoria. Silhueta Porsche inconfundível com presença e funcionalidade.' },
			{ label: 'Uso', texto: 'Espaço para 5 ocupantes, porta-malas generoso e capacidade off-road real. Funciona para família, viagens e lazer.' },
		],
		perfilIdeal: 'Quem precisa de espaço e versatilidade de SUV com a dirigibilidade Porsche. Ideal para famílias que não abrem mão de performance e querem um carro completo para todas as situações.',
		quandoNaoComprar: 'Se o foco é exclusivamente performance pura de esportivo. Apesar de rápido, o Cayenne nunca vai oferecer a mesma conexão com a estrada que um 911 ou Cayman.',
		faq: [
			{ pergunta: 'Qual o preço do Porsche Cayenne no Brasil?', resposta: 'O valor varia amplamente conforme versão (base, S, GTS, Turbo, Turbo GT) e formato (SUV ou Coupé). Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'Cayenne ou Range Rover?', resposta: 'O Cayenne é mais esportivo e dinâmico. O Range Rover prioriza conforto e presença. Para quem valoriza dirigibilidade, o Cayenne é a escolha.' },
			{ pergunta: 'Cayenne diesel ou gasolina?', resposta: 'No Brasil, a maioria das versões disponíveis é gasolina ou híbrida. O diesel era oferecido em gerações anteriores e pode ser encontrado no mercado de seminovos.' },
			{ pergunta: 'A Attra entrega o Cayenne em todo o Brasil?', resposta: 'Sim. Entrega nacional especializada com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
			{ nome: 'Audi Q8', href: '/comprar/modelo/audi-q8' },
			{ nome: 'Range Rover Sport', href: '/comprar/modelo/range-rover-sport' },
		],
	},
	{
		slug: 'porsche-macan',
		brand: 'Porsche',
		model: 'Macan',
		metaTitle: 'Porsche Macan à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Porsche Macan à venda no Brasil. SUV compacto com DNA esportivo Porsche. Preço, versões e estoque. Attra Veículos.',
		keywords: ['porsche macan à venda', 'comprar porsche macan brasil', 'macan preço', 'macan seminovo'],
		resumo: 'O Porsche Macan é o SUV compacto premium mais esportivo do mercado. A porta de entrada para o universo Porsche com praticidade urbana e performance real.',
		versoes: ['Macan', 'Macan S', 'Macan GTS', 'Macan Turbo'],
		faixaPreco: { novo: 'R$ 450 mil a R$ 800 mil', seminovo: 'R$ 250 mil a R$ 600 mil' },
		diferenciais: [
			{ label: 'Performance', texto: 'Plataforma compartilhada com o Audi Q5 mas com chassi Porsche exclusivo. Versão GTS com motor V6 biturbo oferece experiência de condução referência na categoria.' },
			{ label: 'Status', texto: 'Porsche acessível que mantém o DNA da marca. Design compacto e elegante que funciona em qualquer contexto.' },
			{ label: 'Uso', texto: 'Tamanho ideal para uso urbano. Fácil de manobrar e estacionar sem perder a versatilidade de um SUV.' },
		],
		perfilIdeal: 'Quem busca um SUV compacto premium com dirigibilidade esportiva. Ideal para uso urbano diário, sendo a escolha mais popular entre mulheres que buscam conforto, segurança e elegância.',
		quandoNaoComprar: 'Se precisa de muito espaço para passageiros traseiros ou bagagem volumosa. O Macan é compacto e prioriza a experiência do motorista sobre o espaço interno.',
		faq: [
			{ pergunta: 'Qual o preço do Porsche Macan no Brasil?', resposta: 'O Macan é o Porsche mais acessível. O valor depende da versão (base, S, GTS, Turbo) e do ano. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'Macan ou Cayenne?', resposta: 'O Macan é mais compacto, ágil e acessível. O Cayenne oferece mais espaço e versões mais potentes. Para uso urbano, o Macan é mais prático.' },
			{ pergunta: 'O Macan elétrico já está disponível?', resposta: 'O Macan elétrico foi lançado globalmente e começa a chegar ao Brasil. Confira disponibilidade no nosso estoque.' },
			{ pergunta: 'A Attra entrega o Macan em todo o Brasil?', resposta: 'Sim. Entrega nacional em caminhão fechado com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'Audi Q8', href: '/comprar/modelo/audi-q8' },
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
		],
	},
	{
		slug: 'bmw-x5',
		brand: 'BMW',
		model: 'X5',
		metaTitle: 'BMW X5 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'BMW X5 à venda no Brasil. SUV premium com equilíbrio entre performance e conforto. Preço, versões e estoque. Attra Veículos.',
		keywords: ['bmw x5 à venda', 'comprar bmw x5 brasil', 'bmw x5 preço', 'bmw x5 seminovo'],
		resumo: 'O BMW X5 é o SUV premium que equilibra performance esportiva com conforto familiar. Referência na categoria por dirigibilidade e tecnologia embarcada.',
		versoes: ['X5 xDrive40i', 'X5 xDrive45e', 'X5 M50i', 'X5 M Competition'],
		faixaPreco: { novo: 'R$ 600 mil a R$ 1,2 milhão', seminovo: 'R$ 300 mil a R$ 900 mil' },
		diferenciais: [
			{ label: 'Performance', texto: 'Motor 6 cilindros em linha turbo com até 530 cv na versão M50i. Tração integral xDrive com distribuição variável de torque.' },
			{ label: 'Status', texto: 'Um dos SUVs premium mais vendidos globalmente. Combinação de sofisticação e esportividade que define a identidade BMW.' },
			{ label: 'Uso', texto: 'Espaço interno generoso com terceira fileira opcional. Porta-malas amplo e conforto de rodagem para viagens longas.' },
		],
		perfilIdeal: 'Executivos e famílias que precisam de espaço sem abrir mão de performance. O X5 é a escolha para quem quer um SUV completo que entrega tanto na cidade quanto na estrada.',
		quandoNaoComprar: 'Se busca exclusividade extrema ou presença off-road radical. O X5 é eficiente em quase tudo, mas não se destaca em nenhum extremo.',
		faq: [
			{ pergunta: 'Qual o preço do BMW X5 no Brasil?', resposta: 'O valor varia conforme versão (xDrive40i, M50i, M Competition) e quilometragem. Seminovos de 3 a 5 anos oferecem ótimo custo-benefício. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'X5 ou X6?', resposta: 'O X5 oferece mais espaço interno e praticidade. O X6 prioriza design coupé com perfil mais esportivo. Para famílias, o X5 é mais funcional.' },
			{ pergunta: 'O X5 híbrido vale a pena?', resposta: 'O X5 xDrive45e oferece autonomia elétrica de até 80 km, ideal para uso urbano. Combina economia no dia a dia com performance quando necessário.' },
			{ pergunta: 'A Attra entrega o X5 em todo o Brasil?', resposta: 'Sim. Entrega em caminhão fechado com seguro completo para todo o território nacional.' },
		],
		modelosRelacionados: [
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
			{ nome: 'Mercedes GLE', href: '/comprar/modelo/mercedes-gle' },
			{ nome: 'Audi Q7', href: '/comprar/modelo/audi-q7' },
		],
	},
	{
		slug: 'bmw-x6',
		brand: 'BMW',
		model: 'X6',
		metaTitle: 'BMW X6 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'BMW X6 à venda no Brasil. SUV coupé com design arrojado e performance. Preço, versões e estoque real. Attra Veículos.',
		keywords: ['bmw x6 à venda', 'comprar bmw x6 brasil', 'bmw x6 preço', 'bmw x6 seminovo'],
		resumo: 'O BMW X6 é o SUV coupé que criou a categoria. Design provocativo com performance de sedan esportivo em formato utilitário.',
		versoes: ['X6 xDrive40i', 'X6 M50i', 'X6 M Competition'],
		faixaPreco: { novo: 'R$ 650 mil a R$ 1,3 milhão', seminovo: 'R$ 350 mil a R$ 1 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Mesma base mecânica do X5 com centro de gravidade mais baixo pelo teto fastback. Sensação de condução mais conectada que um SUV tradicional.' },
			{ label: 'Status', texto: 'Design coupé arrojado que se destaca no trânsito. Escolha para quem quer impacto visual com praticidade de SUV.' },
			{ label: 'Uso', texto: 'Conforto de SUV com perfil esportivo. Porta-malas menor que o X5 pelo design, mas ainda funcional para uso diário.' },
		],
		perfilIdeal: 'Quem prioriza design e presença visual em um SUV. Ideal para motoristas que dispensam o espaço máximo em favor de uma silhueta mais expressiva e dinâmica.',
		quandoNaoComprar: 'Se precisa de máximo espaço interno e praticidade. O teto inclinado reduz o espaço traseiro e o porta-malas em comparação ao X5.',
		faq: [
			{ pergunta: 'Qual o preço do BMW X6 no Brasil?', resposta: 'O valor depende da versão (xDrive40i, M50i, M Competition) e estado geral. O perfil coupé posiciona o X6 ligeiramente acima do X5. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'X6 ou X5?', resposta: 'O X6 é para quem prioriza design e esportividade. O X5 para quem prioriza espaço e funcionalidade. Mecanicamente, compartilham a mesma base.' },
			{ pergunta: 'O X6 é confortável?', resposta: 'Sim. Apesar do perfil coupé, o X6 mantém o conforto de rodagem BMW. Apenas passageiros mais altos podem notar diferença no espaço traseiro.' },
			{ pergunta: 'A Attra entrega o X6 em todo o Brasil?', resposta: 'Sim. Entrega nacional especializada com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
			{ nome: 'Mercedes GLE', href: '/comprar/modelo/mercedes-gle' },
		],
	},
	{
		slug: 'audi-q7',
		brand: 'Audi',
		model: 'Q7',
		metaTitle: 'Audi Q7 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Audi Q7 à venda no Brasil. SUV de 7 lugares com tecnologia Quattro. Preço, versões e estoque. Attra Veículos.',
		keywords: ['audi q7 à venda', 'comprar audi q7 brasil', 'audi q7 preço', 'audi q7 seminovo'],
		resumo: 'O Audi Q7 é o SUV de grande porte da Audi com 7 lugares reais e tecnologia Quattro. A escolha para famílias que precisam de espaço, conforto e segurança em um pacote premium.',
		versoes: ['Q7 45 TFSI', 'Q7 55 TFSI', 'SQ7'],
		faixaPreco: { novo: 'R$ 500 mil a R$ 900 mil', seminovo: 'R$ 250 mil a R$ 700 mil' },
		diferenciais: [
			{ label: 'Performance', texto: 'Tração integral Quattro com suspensão pneumática. Motor V6 3.0L turbo que entrega potência suave e eficiente para um SUV deste porte.' },
			{ label: 'Status', texto: 'Design sóbrio e elegante. Presença discreta que transmite sofisticação sem ostentação.' },
			{ label: 'Uso', texto: '7 lugares reais com terceira fileira funcional para adultos. Porta-malas de até 890 litros. Ideal para famílias grandes ou viagens com grupo.' },
		],
		perfilIdeal: 'Famílias que precisam de espaço para 7 pessoas com conforto premium. Ideal para viagens longas, golfe no fim de semana ou transporte diário de família com conforto garantido.',
		quandoNaoComprar: 'Se você dirige sozinho na maioria do tempo e não precisa de espaço extra. O Q7 é grande e consome mais que SUVs menores da mesma marca.',
		faq: [
			{ pergunta: 'Qual o preço do Audi Q7 no Brasil?', resposta: 'O valor varia conforme versão (45 TFSI, 55 TFSI, SQ7) e quilometragem. Seminovos de 3 a 5 anos oferecem oportunidades significativas. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'A terceira fileira do Q7 é funcional?', resposta: 'Sim. Diferente de muitos concorrentes, a terceira fileira do Q7 acomoda adultos com razoável conforto, não apenas crianças.' },
			{ pergunta: 'Q7 ou Q8?', resposta: 'O Q7 oferece mais espaço e 7 lugares. O Q8 tem design coupé mais esportivo com 5 lugares. Para famílias, o Q7 é mais funcional.' },
			{ pergunta: 'A Attra entrega o Q7 em todo o Brasil?', resposta: 'Sim. Entrega nacional em caminhão fechado com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
			{ nome: 'Mercedes GLE', href: '/comprar/modelo/mercedes-gle' },
			{ nome: 'Range Rover Sport', href: '/comprar/modelo/range-rover-sport' },
		],
	},
	{
		slug: 'audi-q8',
		brand: 'Audi',
		model: 'Q8',
		metaTitle: 'Audi Q8 à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Audi Q8 à venda no Brasil. SUV coupé de luxo com tecnologia e design premium. Preço, versões e estoque. Attra Veículos.',
		keywords: ['audi q8 à venda', 'comprar audi q8 brasil', 'audi q8 preço', 'audi q8 seminovo'],
		resumo: 'O Audi Q8 é o topo de linha dos SUVs Audi. Design coupé com interior de referência em tecnologia e qualidade de acabamento.',
		versoes: ['Q8 55 TFSI', 'SQ8', 'RS Q8'],
		faixaPreco: { novo: 'R$ 700 mil a R$ 1,5 milhão', seminovo: 'R$ 400 mil a R$ 1,2 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Versão RS Q8 com motor V8 4.0L biturbo de 600 cv. Recordista do Nürburgring para SUVs. Tração Quattro e suspensão adaptativa de série.' },
			{ label: 'Status', texto: 'Topo da gama Audi com design Singleframe imponente. Combina luxo e esportividade em um pacote exclusivo.' },
			{ label: 'Uso', texto: 'Interior com dupla tela tátil e Virtual Cockpit. Conforto de primeiro nível para 5 ocupantes com porta-malas generoso.' },
		],
		perfilIdeal: 'Executivos que querem o melhor da Audi em formato SUV. Ideal para quem busca tecnologia de ponta, conforto supremo e design que se diferencia no segmento.',
		quandoNaoComprar: 'Se precisa de 7 lugares, o Q7 é a escolha. O Q8 sacrifica espaço da terceira fileira pelo design coupé.',
		faq: [
			{ pergunta: 'Qual o preço do Audi Q8 no Brasil?', resposta: 'O valor depende da versão (55 TFSI, SQ8, RS Q8). Versões RS mantêm valor acima da média pela exclusividade. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'RS Q8 ou Cayenne Turbo?', resposta: 'O RS Q8 tem mais tecnologia embarcada e interior mais moderno. O Cayenne Turbo tem chassis mais esportivo e melhor feedback de condução. Ambos entregam performance excepcional.' },
			{ pergunta: 'O Q8 é confortável para viagens?', resposta: 'Extremamente. Suspensão pneumática, isolamento acústico e bancos multicontorno fazem dele um dos SUVs mais confortáveis do mercado.' },
			{ pergunta: 'A Attra entrega o Q8 em todo o Brasil?', resposta: 'Sim. Entrega especializada nacional com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
			{ nome: 'BMW X6', href: '/comprar/modelo/bmw-x6' },
			{ nome: 'Range Rover Sport', href: '/comprar/modelo/range-rover-sport' },
		],
	},
	{
		slug: 'range-rover-sport',
		brand: 'Land Rover',
		model: 'Range Rover Sport',
		metaTitle: 'Range Rover Sport à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Range Rover Sport à venda no Brasil. SUV esportivo de luxo com capacidade off-road. Preço, versões e estoque. Attra Veículos.',
		keywords: ['range rover sport à venda', 'comprar range rover sport brasil', 'range rover sport preço', 'range rover sport seminovo'],
		resumo: 'O Range Rover Sport combina luxo britânico com capacidade off-road real e performance esportiva. Escolha para quem quer presença, conforto e versatilidade total.',
		versoes: ['Sport P360', 'Sport P400', 'Sport P530', 'Sport SVR'],
		faixaPreco: { novo: 'R$ 700 mil a R$ 1,5 milhão', seminovo: 'R$ 350 mil a R$ 1,2 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Versão SVR com motor V8 5.0L supercharged de 575 cv. Suspensão pneumática com ajuste de altura para asfalto e off-road.' },
			{ label: 'Status', texto: 'Ícone de luxo esportivo britânico. Presença de rua inconfundível que transmite poder e sofisticação.' },
			{ label: 'Uso', texto: 'Conforto de Range Rover com perfil mais dinâmico. Capacidade real de off-road mantida com performance de estrada superior.' },
		],
		perfilIdeal: 'Quem busca presença marcante com versatilidade total. Ideal para uso em fazendas, golfe e estrada sem abrir mão de luxo e performance no asfalto.',
		quandoNaoComprar: 'Se busca economia de manutenção e consumo. Range Rover Sport tem custo de propriedade elevado e pode ter questões de confiabilidade eletrônica em modelos mais antigos.',
		faq: [
			{ pergunta: 'Qual o preço do Range Rover Sport no Brasil?', resposta: 'O valor varia significativamente conforme motorização (P360, P400, P530, SVR). Consulte nosso estoque para preços atualizados e condições reais.' },
			{ pergunta: 'Range Rover Sport ou Cayenne?', resposta: 'O Cayenne é mais esportivo no asfalto. O Range Rover Sport oferece melhor capacidade off-road e interior mais luxuoso. Depende do uso prioritário.' },
			// REVISAR ANUALMENTE — referência a "nova geração" envelhece com lançamentos
			{ pergunta: 'O Range Rover Sport é confiável?', resposta: 'A nova geração melhorou significativamente em confiabilidade. Recomenda-se manutenção preventiva rigorosa e preferir veículos com histórico completo de revisões.' },
			{ pergunta: 'A Attra entrega o Range Rover Sport em todo o Brasil?', resposta: 'Sim. Entrega nacional em caminhão fechado com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
			{ nome: 'Land Rover Defender', href: '/comprar/modelo/land-rover-defender' },
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
		],
	},
	{
		slug: 'land-rover-defender',
		brand: 'Land Rover',
		model: 'Defender',
		metaTitle: 'Land Rover Defender à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Land Rover Defender à venda no Brasil. Ícone off-road com design moderno. Preço, versões e estoque real. Attra Veículos.',
		keywords: ['land rover defender à venda', 'comprar defender brasil', 'defender preço', 'defender seminovo'],
		resumo: 'O Land Rover Defender é o veículo off-road mais icônico do mundo, agora com tecnologia moderna e conforto premium. Projetado para quem recusa limites geográficos.',
		versoes: ['Defender 90', 'Defender 110', 'Defender 130', 'Defender V8'],
		faixaPreco: { novo: 'R$ 500 mil a R$ 1,2 milhão', seminovo: 'R$ 350 mil a R$ 1 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Versão V8 com 525 cv sobre plataforma off-road. Chassi monobloco com geometria específica para terrenos extremos e ângulos de ataque superiores.' },
			{ label: 'Status', texto: 'Ícone global de aventura e robustez. Design que comunica personalidade forte e independência.' },
			{ label: 'Uso', texto: 'Capacidade off-road real que poucos veículos igualam. Disponível em 3 comprimentos (90, 110, 130) para diferentes necessidades.' },
		],
		perfilIdeal: 'Aventureiros e proprietários rurais que precisam de capacidade off-road real. Também para quem valoriza o estilo robusto e a personalidade única do Defender na cidade.',
		quandoNaoComprar: 'Se busca conforto de rodagem refinado no asfalto. O Defender prioriza robustez sobre suavidade. Para estrada, um Range Rover Sport é mais confortável.',
		faq: [
			{ pergunta: 'Qual o preço do Defender no Brasil?', resposta: 'O valor depende do comprimento (90, 110, 130) e motorização. Alta demanda mantém valores elevados nos primeiros anos. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'Defender 90 ou 110?', resposta: 'O 90 é mais compacto e ágil, ideal para uso urbano e trilhas. O 110 oferece mais espaço para família e bagagem. O 130 tem a maior capacidade de carga e 8 lugares.' },
			{ pergunta: 'O Defender novo é bom como o antigo?', resposta: 'O novo Defender combina a capacidade off-road lendária com tecnologia e conforto modernos. É superior em quase todos os aspectos técnicos ao modelo anterior.' },
			{ pergunta: 'A Attra entrega o Defender em todo o Brasil?', resposta: 'Sim. Entrega nacional em caminhão fechado com seguro completo.' },
		],
		modelosRelacionados: [
			{ nome: 'Range Rover Sport', href: '/comprar/modelo/range-rover-sport' },
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
		],
	},
	{
		slug: 'mercedes-gle',
		brand: 'Mercedes-Benz',
		model: 'GLE',
		metaTitle: 'Mercedes GLE à Venda no Brasil | Preço e Estoque | Attra Veículos',
		metaDescription: 'Mercedes GLE à venda no Brasil. SUV premium com conforto e tecnologia de referência. Preço, versões e estoque. Attra Veículos.',
		keywords: ['mercedes gle à venda', 'comprar mercedes gle brasil', 'mercedes gle preço', 'gle seminovo'],
		resumo: 'O Mercedes-Benz GLE é o SUV premium que prioriza conforto e refinamento acima de tudo. A escolha para quem busca o interior mais luxuoso da categoria.',
		versoes: ['GLE 300 d', 'GLE 400 d', 'GLE 450', 'GLE 53 AMG', 'GLE 63 AMG S'],
		faixaPreco: { novo: 'R$ 550 mil a R$ 1,3 milhão', seminovo: 'R$ 300 mil a R$ 1 milhão' },
		diferenciais: [
			{ label: 'Performance', texto: 'Versão AMG 63 S com motor V8 biturbo de 612 cv. Suspensão E-Active Body Control que elimina inclinação em curvas.' },
			{ label: 'Status', texto: 'Mercedes-Benz como sinônimo de luxo. O GLE representa o equilíbrio perfeito entre tamanho, presença e sofisticação.' },
			{ label: 'Uso', texto: 'Interior MBUX de referência com dupla tela widescreen. Isolamento acústico excepcional e bancos que rivalizam com poltronas de primeira classe.' },
		],
		perfilIdeal: 'Executivos e famílias que priorizam conforto absoluto e tecnologia de ponta. O GLE é para quem quer chegar descansado após horas de viagem e impressionar em qualquer ocasião.',
		quandoNaoComprar: 'Se a prioridade é dirigibilidade esportiva pura. O GLE prioriza conforto sobre esportividade, mesmo nas versões AMG.',
		faq: [
			{ pergunta: 'Qual o preço do Mercedes GLE no Brasil?', resposta: 'O valor varia conforme versão (GLE 450, AMG 53, AMG 63 S). Versões AMG mantêm valor acima da média. Consulte nosso estoque para preços atualizados.' },
			{ pergunta: 'GLE ou BMW X5?', resposta: 'O GLE é mais confortável e luxuoso no interior. O X5 é mais esportivo e dinâmico na condução. Para conforto, GLE. Para dirigibilidade, X5.' },
			{ pergunta: 'O GLE Coupé vale a pena?', resposta: 'O GLE Coupé sacrifica espaço pelo design fastback. Para quem prioriza presença visual sobre funcionalidade, é uma alternativa atraente.' },
			{ pergunta: 'A Attra entrega o GLE em todo o Brasil?', resposta: 'Sim. Entrega em caminhão fechado com seguro completo para todo o território nacional.' },
		],
		modelosRelacionados: [
			{ nome: 'BMW X5', href: '/comprar/modelo/bmw-x5' },
			{ nome: 'Porsche Cayenne', href: '/comprar/modelo/porsche-cayenne' },
			{ nome: 'Audi Q7', href: '/comprar/modelo/audi-q7' },
		],
	},
]

// ---------------------------------------------------------------------------
