export interface PrecoPage {
	slug: string
	brand: string
	model: string
	metaTitle: string
	metaDescription: string
	keywords: string[]
	faixaGeral: string // Faixa ampla qualitativa (ex: "entrada do segmento esportivo até topo de linha GT")
	diferencaVersoes: string
	fatoresPreco: string[]
	novoVsSeminovo: string
	valeAPena: string
	modeloSlug: string
}

export const PRECOS: PrecoPage[] = [
	{
		slug: 'porsche-911-brasil',
		brand: 'Porsche', model: '911',
		metaTitle: 'Preço Porsche 911 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Porsche 911 no Brasil atualizado. Faixa de preço novo e seminovo, diferença entre versões e fatores que impactam o valor. Attra Veículos.',
		keywords: ['preço porsche 911', 'porsche 911 preço brasil', 'quanto custa porsche 911', 'porsche 911 valor'],
		faixaGeral: 'O 911 tem faixa ampla: a versão Carrera base representa a entrada do segmento, enquanto as versões GT e Turbo S posicionam-se no topo de linha, com variação significativa entre zero km e seminovos bem conservados. Consulte valores atualizados diretamente no estoque.',
		diferencaVersoes: 'A versão Carrera base parte do menor valor. A Turbo S e GT3 RS são as mais valorizadas. Versões GT mantêm ou até valorizam com o tempo, especialmente com baixa quilometragem.',
		fatoresPreco: ['Quilometragem (abaixo de 20 mil km valoriza significativamente)', 'Histórico completo na rede autorizada', 'Opcionais de fábrica (PCCB, Sport Chrono, cores especiais)', 'Condição dos pneus e freios (especialmente cerâmicos)'],
		novoVsSeminovo: 'O 911 seminovo é uma das melhores compras do segmento esportivo. Modelos com 2 a 3 anos perdem entre 15% e 25% do valor de zero km, enquanto oferecem a mesma experiência de condução. Versões GT são exceção: muitas valorizam acima do preço de tabela.',
		valeAPena: 'Sim. O Porsche 911 é um dos veículos esportivos que menos deprecia no mercado brasileiro. É investimento e experiência de condução ao mesmo tempo.',
		modeloSlug: 'porsche-911',
	},
	{
		slug: 'bmw-m3-brasil',
		brand: 'BMW', model: 'M3',
		metaTitle: 'Preço BMW M3 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do BMW M3 no Brasil atualizado. Faixa de preço novo e seminovo, versões e fatores que impactam o valor. Attra Veículos.',
		keywords: ['preço bmw m3', 'bmw m3 preço brasil', 'quanto custa bmw m3', 'bmw m3 valor'],
		faixaGeral: 'O M3 posiciona-se no segmento intermediário de sedans esportivos. A versão Standard é a entrada; Competition e CS elevam consideravelmente o valor. Seminovos da geração anterior oferecem excelente relação custo-performance. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O M3 Standard é a versão de entrada. O Competition adiciona potência e diferencial ativo. O CS é a versão mais exclusiva com menos peso e mais potência.',
		fatoresPreco: ['Quilometragem e histórico de uso (pista x rua)', 'Versão (Standard, Competition, xDrive, CS)', 'Condição do motor S58 e câmbio', 'Opcionais como bancos M e pacote Carbon'],
		novoVsSeminovo: 'O M3 seminovo da geração G80 oferece boa relação custo-performance. A geração anterior F80 é mais acessível e ainda muito competente. A depreciação inicial é de 20% a 30% nos primeiros 3 anos.',
		valeAPena: 'Para entusiastas de condução, o M3 é uma das melhores compras no segmento de sedans esportivos. Performance de pista em um carro funcional de 4 portas.',
		modeloSlug: 'bmw-m3',
	},
	{
		slug: 'mercedes-c63-amg-brasil',
		brand: 'Mercedes-Benz', model: 'C63 AMG',
		metaTitle: 'Preço Mercedes C63 AMG no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Mercedes C63 AMG no Brasil. Faixa de preço V8 e híbrido, diferença entre versões. Attra Veículos.',
		keywords: ['preço mercedes c63 amg', 'c63 amg preço brasil', 'quanto custa c63 amg', 'mercedes amg c63 valor'],
		// REVISAR ANUALMENTE — referência a "nova geração" envelhece com lançamentos
		faixaGeral: 'O C63 AMG abrange desde versões de entrada até a linha S de alta performance. As versões V8 (W205) estão em tendência de valorização pela descontinuação do motor. A nova geração híbrida reposiciona o modelo. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'A versão S entrega mais potência e equipamentos. O Coupé tem visual mais esportivo. A nova geração W206 com 4 cilindros híbrido divide opiniões, mas oferece potência superior com auxílio elétrico.',
		fatoresPreco: ['Motor V8 (W205) vs 4 cilindros híbrido (W206)', 'Quilometragem e histórico de manutenção AMG', 'Versão (C 63, C 63 S, C 63 S Coupé)', 'Condição dos pneus e sistema de freios AMG'],
		novoVsSeminovo: 'As versões V8 (W205) estão se valorizando no mercado de seminovos por serem as últimas da linhagem V8. Comprar um V8 bem conservado pode ser investimento de médio prazo.',
		valeAPena: 'Sim, especialmente as versões V8. A combinação de sonoridade, performance e luxo Mercedes é única no segmento. As versões V8 tendem a se valorizar com o fim da produção.',
		modeloSlug: 'mercedes-c63-amg',
	},
	{
		slug: 'audi-rs6-brasil',
		brand: 'Audi', model: 'RS6',
		metaTitle: 'Preço Audi RS6 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Audi RS6 Avant no Brasil. Faixa de preço, versões e análise de valor. Attra Veículos.',
		keywords: ['preço audi rs6', 'audi rs6 preço brasil', 'quanto custa audi rs6', 'audi rs6 avant valor'],
		faixaGeral: 'O RS6 Avant é posicionado no topo do segmento de peruas esportivas. A exclusividade e o motor V8 biturbo mantêm alto valor de revenda. Seminovos recentes depreciam moderadamente. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O RS6 Avant Standard já vem completo. A versão Performance adiciona 30 cv e detalhes exclusivos. Ambas compartilham o mesmo motor V8 4.0L biturbo.',
		fatoresPreco: ['Quilometragem (RS6 com menos de 15 mil km mantém valor alto)', 'Pacote de opcionais (Dynamic, Design, Black Optic)', 'Histórico completo na rede Audi', 'Condição da suspensão pneumática'],
		novoVsSeminovo: 'O RS6 seminovo recente é uma compra inteligente. A depreciação nos primeiros 2 anos é moderada (15% a 20%) e o carro mantém alto valor de revenda pela exclusividade.',
		valeAPena: 'Absolutamente. Não existe outro carro que combine V8 biturbo, 600 cv, espaço familiar e formato perua. É único no mercado.',
		modeloSlug: 'audi-rs6',
	},
	{
		slug: 'porsche-cayenne-brasil',
		brand: 'Porsche', model: 'Cayenne',
		metaTitle: 'Preço Porsche Cayenne no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Porsche Cayenne no Brasil. Todas as versões, faixa de preço novo e seminovo. Attra Veículos.',
		keywords: ['preço porsche cayenne', 'cayenne preço brasil', 'quanto custa porsche cayenne', 'cayenne valor'],
		faixaGeral: 'O Cayenne varia bastante conforme versão: a base é a entrada do portfólio SUV Porsche, enquanto Turbo GT representa o topo. O formato Coupé tem posicionamento ligeiramente acima do SUV convencional. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O Cayenne base já é completo. S e GTS oferecem mais potência. Turbo e Turbo GT são as versões de performance extrema. E-Hybrid combina economia urbana com potência.',
		fatoresPreco: ['Versão (base, S, GTS, Turbo, Turbo GT, E-Hybrid)', 'Quilometragem e histórico de revisões Porsche', 'Opcionais (PASM, ar condicionado 4 zonas, Pack Sport)', 'Formato (SUV ou Coupé)'],
		novoVsSeminovo: 'O Cayenne seminovo é excelente compra. A depreciação nos primeiros 3 anos é de 20% a 30%. Versões de 3 a 5 anos oferecem ótimo custo-benefício mantendo a qualidade Porsche.',
		valeAPena: 'Sim. O Cayenne é referência em SUVs esportivos e mantém valor de revenda consistente. É a porta de entrada mais prática para o universo Porsche.',
		modeloSlug: 'porsche-cayenne',
	},
	{
		slug: 'porsche-macan-brasil',
		brand: 'Porsche', model: 'Macan',
		metaTitle: 'Preço Porsche Macan no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Porsche Macan no Brasil. Faixa de preço novo e seminovo, versões disponíveis. Attra Veículos.',
		keywords: ['preço porsche macan', 'macan preço brasil', 'quanto custa porsche macan', 'macan valor'],
		faixaGeral: 'O Macan é a forma mais acessível de entrar no universo Porsche. A versão base é competitiva no segmento de SUVs compactos premium, enquanto o GTS e Turbo elevam o posicionamento. Seminovos oferecem desconto significativo sobre o zero km. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O Macan base é a versão mais acessível da Porsche. GTS com V6 biturbo é a versão com melhor custo-benefício em performance. Turbo é o topo com máxima potência.',
		fatoresPreco: ['Versão (base, S, GTS, Turbo)', 'Quilometragem e revisões na rede Porsche', 'Opcionais (Sport Chrono, PASM, teto panorâmico)', 'Geração do modelo'],
		novoVsSeminovo: 'O Macan é o Porsche mais acessível e um dos que mais deprecia nos primeiros anos (25% a 35%). Isso o torna uma excelente compra como seminovo.',
		valeAPena: 'Sim. É a forma mais acessível de ter um Porsche legítimo com excelente dirigibilidade no dia a dia urbano.',
		modeloSlug: 'porsche-macan',
	},
	{
		slug: 'bmw-x5-brasil',
		brand: 'BMW', model: 'X5',
		metaTitle: 'Preço BMW X5 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do BMW X5 no Brasil. Faixa de preço, versões e comparação novo vs seminovo. Attra Veículos.',
		keywords: ['preço bmw x5', 'bmw x5 preço brasil', 'quanto custa bmw x5', 'bmw x5 valor'],
		faixaGeral: 'O X5 posiciona-se no centro do segmento de SUVs premium. O xDrive40i é o mais equilibrado, enquanto o M50i e M Competition ocupam patamares superiores. Seminovos de 3 a 5 anos oferecem ótimo custo-benefício. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O xDrive40i é a versão mais equilibrada. O M50i entrega performance com motor V8. O X5 M Competition é o extremo com mais de 600 cv.',
		fatoresPreco: ['Versão e motorização', 'Quilometragem e histórico BMW', 'Pacote de opcionais e acabamento', 'Condição da suspensão e eletrônica'],
		novoVsSeminovo: 'O X5 seminovo é uma compra inteligente. A depreciação dos primeiros 3 anos é de 25% a 35%, oferecendo acesso a um SUV premium completo por valor significativamente menor.',
		valeAPena: 'Sim. O X5 é um dos SUVs premium mais completos do mercado, equilibrando esportividade, espaço e tecnologia.',
		modeloSlug: 'bmw-x5',
	},
	{
		slug: 'bmw-x6-brasil',
		brand: 'BMW', model: 'X6',
		metaTitle: 'Preço BMW X6 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do BMW X6 no Brasil. SUV coupé com preço, versões e análise de valor. Attra Veículos.',
		keywords: ['preço bmw x6', 'bmw x6 preço brasil', 'quanto custa bmw x6', 'bmw x6 valor'],
		faixaGeral: 'O X6 tem posicionamento ligeiramente acima do X5 pelo perfil coupé. O xDrive40i é a versão principal, M50i e X6 M Competition representam o topo. Deprecia um pouco mais que o X5 nos primeiros anos. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O X6 xDrive40i é a versão mais vendida. O M50i adiciona motor V8. O X6 M Competition é a versão de performance máxima.',
		fatoresPreco: ['Versão e motorização', 'Quilometragem e histórico', 'Acabamento interno e opcionais', 'Condição geral do veículo'],
		novoVsSeminovo: 'O X6 deprecia ligeiramente mais que o X5 pelo perfil menos prático. Seminovos de 2 a 4 anos oferecem desconto de 30% a 40% sobre o zero km.',
		valeAPena: 'Sim, para quem valoriza o design coupé sobre a praticidade. O X6 oferece a mesma experiência BMW com uma estética diferenciada.',
		modeloSlug: 'bmw-x6',
	},
	{
		slug: 'audi-q7-brasil',
		brand: 'Audi', model: 'Q7',
		metaTitle: 'Preço Audi Q7 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Audi Q7 no Brasil. SUV 7 lugares com preço, versões e análise. Attra Veículos.',
		keywords: ['preço audi q7', 'audi q7 preço brasil', 'quanto custa audi q7', 'audi q7 valor'],
		faixaGeral: 'O Q7 posiciona-se na faixa intermediária dos SUVs premium de 7 lugares. O 45 TFSI é a entrada, enquanto o SQ7 eleva significativamente o valor. Seminovos de 3 a 5 anos depreciam consideravelmente, criando oportunidades. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O Q7 45 TFSI é a versão de entrada. O 55 TFSI oferece mais potência com motor V6. O SQ7 é a versão de performance com motor V8 diesel ou gasolina.',
		fatoresPreco: ['Versão e motorização', 'Quilometragem e revisões Audi', 'Condição da terceira fileira e interiores', 'Suspensão pneumática (quando equipado)'],
		novoVsSeminovo: 'O Q7 tem depreciação moderada a alta nos primeiros anos (30% a 40%). Isso torna os seminovos de 3 a 5 anos excelentes oportunidades para quem busca 7 lugares premium.',
		valeAPena: 'Sim. É um dos poucos SUVs premium com 7 lugares reais e funcionalidade Quattro completa.',
		modeloSlug: 'audi-q7',
	},
	{
		slug: 'audi-q8-brasil',
		brand: 'Audi', model: 'Q8',
		metaTitle: 'Preço Audi Q8 no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Audi Q8 no Brasil. SUV coupé de luxo com preço, versões e análise. Attra Veículos.',
		keywords: ['preço audi q8', 'audi q8 preço brasil', 'quanto custa audi q8', 'audi q8 valor'],
		faixaGeral: 'O Q8 posiciona-se no segmento alto dos SUVs coupé. O 55 TFSI é a versão principal, SQ8 adiciona performance, e o RS Q8 é o topo absoluto da linha. Versões RS mantêm valor acima da média pela exclusividade. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O Q8 55 TFSI é a versão principal. O SQ8 adiciona V8 diesel. O RS Q8 é o topo absoluto com V8 gasolina biturbo.',
		fatoresPreco: ['Versão (55 TFSI, SQ8, RS Q8)', 'Quilometragem e estado geral', 'Pacote tecnológico (dupla tela, head-up display)', 'Condição da suspensão adaptativa'],
		novoVsSeminovo: 'O Q8 deprecia entre 25% e 35% nos primeiros 3 anos. Versões RS Q8 mantêm valor acima da média pela exclusividade e performance.',
		valeAPena: 'Sim, especialmente como seminovo. Oferece o melhor da tecnologia Audi com design premium e presença marcante.',
		modeloSlug: 'audi-q8',
	},
	{
		slug: 'range-rover-sport-brasil',
		brand: 'Land Rover', model: 'Range Rover Sport',
		metaTitle: 'Preço Range Rover Sport no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Range Rover Sport no Brasil. Faixa de preço, versões e comparação. Attra Veículos.',
		keywords: ['preço range rover sport', 'range rover sport preço brasil', 'quanto custa range rover sport', 'range rover sport valor'],
		faixaGeral: 'O Range Rover Sport tem variação ampla conforme motorização: P360 e P400 são as versões mais acessíveis, enquanto SVR com V8 supercharged ocupa o topo. Deprecia consideravelmente nos primeiros anos, criando boas oportunidades em seminovos. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'P360 e P400 são versões 6 cilindros. P530 com V8. SVR é a versão de performance com V8 supercharged de 575 cv.',
		fatoresPreco: ['Versão e motorização', 'Quilometragem e histórico na rede Land Rover', 'Condição eletrônica e suspensão pneumática', 'Opcionais (teto panorâmico, sistema Meridian)'],
		novoVsSeminovo: 'O Range Rover Sport deprecia significativamente nos primeiros anos (30% a 45%). Seminovos de 3 a 5 anos são oportunidades reais de custo-benefício.',
		valeAPena: 'Sim, especialmente como seminovo bem conservado. A presença e o conforto justificam o investimento quando o veículo tem histórico limpo.',
		modeloSlug: 'range-rover-sport',
	},
	{
		slug: 'land-rover-defender-brasil',
		brand: 'Land Rover', model: 'Defender',
		metaTitle: 'Preço Land Rover Defender no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Land Rover Defender no Brasil. Versões 90, 110, 130 e V8. Faixa de preço e análise. Attra Veículos.',
		keywords: ['preço land rover defender', 'defender preço brasil', 'quanto custa defender', 'defender valor'],
		faixaGeral: 'O Defender tem alta demanda e filas de espera, mantendo valores de seminovos próximos aos de zero km nos primeiros anos. O 90 é o mais compacto, o 110 o mais equilibrado, e o V8 é a versão de performance. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O Defender 90 é o mais compacto. O 110 é o mais equilibrado para famílias. O 130 tem capacidade máxima. O V8 é a versão de performance com 525 cv.',
		fatoresPreco: ['Comprimento (90, 110, 130)', 'Motorização (4 cilindros, 6 cilindros, V8)', 'Quilometragem e uso (estrada x off-road)', 'Acessórios e preparação off-road'],
		novoVsSeminovo: 'O Defender tem alta demanda e filas de espera, o que mantém preços de seminovos próximos aos de zero km nos primeiros 2 anos. Após esse período, a depreciação começa a se normalizar.',
		valeAPena: 'Sim. É um veículo icônico com alta procura. A versão 110 oferece o melhor equilíbrio entre praticidade e presença.',
		modeloSlug: 'land-rover-defender',
	},
	{
		slug: 'mercedes-gle-brasil',
		brand: 'Mercedes-Benz', model: 'GLE',
		metaTitle: 'Preço Mercedes GLE no Brasil | Tabela Atualizada | Attra Veículos',
		metaDescription: 'Preço do Mercedes GLE no Brasil. Faixa de preço, versões e comparação novo vs seminovo. Attra Veículos.',
		keywords: ['preço mercedes gle', 'mercedes gle preço brasil', 'quanto custa mercedes gle', 'mercedes gle valor'],
		faixaGeral: 'O GLE posiciona-se no centro do segmento de SUVs premium. O GLE 450 é a versão mais equilibrada, AMG 53 adiciona esportividade, e o AMG 63 S é o topo com performance extrema. Versões AMG mantêm valor acima da média. Consulte valores atualizados no estoque.',
		diferencaVersoes: 'O GLE 450 é a versão mais equilibrada. O AMG 53 adiciona esportividade. O AMG 63 S é o extremo com V8 biturbo de 612 cv.',
		fatoresPreco: ['Versão e motorização', 'Quilometragem e histórico Mercedes', 'Condição do sistema MBUX e eletrônica', 'Pacote de opcionais (AMG Line, Burmester, etc.)'],
		novoVsSeminovo: 'O GLE deprecia entre 25% e 35% nos primeiros 3 anos. Versões AMG mantêm valor acima da média. Seminovos de 2 a 4 anos oferecem excelente custo-benefício.',
		valeAPena: 'Sim. O GLE é referência em conforto e tecnologia na categoria. Seminovos bem conservados entregam uma experiência premium a um preço acessível.',
		modeloSlug: 'mercedes-gle',
	},
]

// ---------------------------------------------------------------------------
